### ISSUE TITLE
Tweepy v4 breaking changes

### ISSUE THREAD

**Issue by a4vg** [bshmueli/SPIRS#3]
Tweepy introduced breaking changes in v4 that affect `fetch-tweets.py`. After looking at [the changelog](https://github.com/tweepy/tweepy/blob/8f648b688a86f0ffe33319fac7d75d7d4708437f/docs/changelog.md#breaking-changes), a couple of changes should be made:
 * Remove `wait_on_rate_limit_notify=True` [(line 51)](https://github.com/bshmueli/SPIRS/blob/master/fetch-tweets.py#L51)
 * Change `api.statuses_lookup` for `api.lookup_statuses` [(line 19)](https://github.com/bshmueli/SPIRS/blob/5e389fe02f3f539ad2c06e40e7fb87545a5d027b/fetch-tweets.py#L19).

Or simply updating the README with a specific version of tweepy (<v4) will work. I've submitted a pull request #4 if you prefer to go with the code changes.

**Comment by bshmueli** [comment]
Thank you Andrea! Just merged your pull request into the main branch.
