### ISSUE TITLE
Twitter api quota limitation

### ISSUE THREAD

**Issue by Reze-Joe** [bshmueli/SPIRS#5]
Hi team, thanks for your efforts!

Because of the limitation of the Twitter API quota, I couldn't get the full dataset through the method provided in README. So I'm wondering if it's possible to get the dataset (even some samples) somehow?

**Comment by bshmueli** [comment]
I suggest contacting the paper's corresponding author by email.

**Comment by bshmueli** [comment]
I suggest contacting the paper's corresponding author by email.
